// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: system_service.proto
#ifndef GRPC_system_5fservice_2eproto__INCLUDED
#define GRPC_system_5fservice_2eproto__INCLUDED

#include "system_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace controller {

class SystemService final {
 public:
  static constexpr char const* service_full_name() {
    return "controller.SystemService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::controller::VersionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::controller::VersionResponse>> AsyncGetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::controller::VersionResponse>>(AsyncGetVersionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::controller::VersionResponse>> PrepareAsyncGetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::controller::VersionResponse>>(PrepareAsyncGetVersionRaw(context, request, cq));
    }
    virtual ::grpc::Status ClearError(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::controller::ErrorClearResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::controller::ErrorClearResponse>> AsyncClearError(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::controller::ErrorClearResponse>>(AsyncClearErrorRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::controller::ErrorClearResponse>> PrepareAsyncClearError(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::controller::ErrorClearResponse>>(PrepareAsyncClearErrorRaw(context, request, cq));
    }
    virtual ::grpc::Status EnableController(::grpc::ClientContext* context, const ::controller::EnableControllerRequest& request, ::controller::EnableControllerResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::controller::EnableControllerResponse>> AsyncEnableController(::grpc::ClientContext* context, const ::controller::EnableControllerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::controller::EnableControllerResponse>>(AsyncEnableControllerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::controller::EnableControllerResponse>> PrepareAsyncEnableController(::grpc::ClientContext* context, const ::controller::EnableControllerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::controller::EnableControllerResponse>>(PrepareAsyncEnableControllerRaw(context, request, cq));
    }
    virtual ::grpc::Status IsEnabledController(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::controller::IsEnabledControllerResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::controller::IsEnabledControllerResponse>> AsyncIsEnabledController(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::controller::IsEnabledControllerResponse>>(AsyncIsEnabledControllerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::controller::IsEnabledControllerResponse>> PrepareAsyncIsEnabledController(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::controller::IsEnabledControllerResponse>>(PrepareAsyncIsEnabledControllerRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::controller::VersionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::controller::VersionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ClearError(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::controller::ErrorClearResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ClearError(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::controller::ErrorClearResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void EnableController(::grpc::ClientContext* context, const ::controller::EnableControllerRequest* request, ::controller::EnableControllerResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void EnableController(::grpc::ClientContext* context, const ::controller::EnableControllerRequest* request, ::controller::EnableControllerResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void IsEnabledController(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::controller::IsEnabledControllerResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void IsEnabledController(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::controller::IsEnabledControllerResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::controller::VersionResponse>* AsyncGetVersionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::controller::VersionResponse>* PrepareAsyncGetVersionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::controller::ErrorClearResponse>* AsyncClearErrorRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::controller::ErrorClearResponse>* PrepareAsyncClearErrorRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::controller::EnableControllerResponse>* AsyncEnableControllerRaw(::grpc::ClientContext* context, const ::controller::EnableControllerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::controller::EnableControllerResponse>* PrepareAsyncEnableControllerRaw(::grpc::ClientContext* context, const ::controller::EnableControllerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::controller::IsEnabledControllerResponse>* AsyncIsEnabledControllerRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::controller::IsEnabledControllerResponse>* PrepareAsyncIsEnabledControllerRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::controller::VersionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::controller::VersionResponse>> AsyncGetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::controller::VersionResponse>>(AsyncGetVersionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::controller::VersionResponse>> PrepareAsyncGetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::controller::VersionResponse>>(PrepareAsyncGetVersionRaw(context, request, cq));
    }
    ::grpc::Status ClearError(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::controller::ErrorClearResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::controller::ErrorClearResponse>> AsyncClearError(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::controller::ErrorClearResponse>>(AsyncClearErrorRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::controller::ErrorClearResponse>> PrepareAsyncClearError(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::controller::ErrorClearResponse>>(PrepareAsyncClearErrorRaw(context, request, cq));
    }
    ::grpc::Status EnableController(::grpc::ClientContext* context, const ::controller::EnableControllerRequest& request, ::controller::EnableControllerResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::controller::EnableControllerResponse>> AsyncEnableController(::grpc::ClientContext* context, const ::controller::EnableControllerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::controller::EnableControllerResponse>>(AsyncEnableControllerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::controller::EnableControllerResponse>> PrepareAsyncEnableController(::grpc::ClientContext* context, const ::controller::EnableControllerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::controller::EnableControllerResponse>>(PrepareAsyncEnableControllerRaw(context, request, cq));
    }
    ::grpc::Status IsEnabledController(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::controller::IsEnabledControllerResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::controller::IsEnabledControllerResponse>> AsyncIsEnabledController(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::controller::IsEnabledControllerResponse>>(AsyncIsEnabledControllerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::controller::IsEnabledControllerResponse>> PrepareAsyncIsEnabledController(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::controller::IsEnabledControllerResponse>>(PrepareAsyncIsEnabledControllerRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::controller::VersionResponse* response, std::function<void(::grpc::Status)>) override;
      void GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::controller::VersionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ClearError(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::controller::ErrorClearResponse* response, std::function<void(::grpc::Status)>) override;
      void ClearError(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::controller::ErrorClearResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void EnableController(::grpc::ClientContext* context, const ::controller::EnableControllerRequest* request, ::controller::EnableControllerResponse* response, std::function<void(::grpc::Status)>) override;
      void EnableController(::grpc::ClientContext* context, const ::controller::EnableControllerRequest* request, ::controller::EnableControllerResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void IsEnabledController(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::controller::IsEnabledControllerResponse* response, std::function<void(::grpc::Status)>) override;
      void IsEnabledController(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::controller::IsEnabledControllerResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::controller::VersionResponse>* AsyncGetVersionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::controller::VersionResponse>* PrepareAsyncGetVersionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::controller::ErrorClearResponse>* AsyncClearErrorRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::controller::ErrorClearResponse>* PrepareAsyncClearErrorRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::controller::EnableControllerResponse>* AsyncEnableControllerRaw(::grpc::ClientContext* context, const ::controller::EnableControllerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::controller::EnableControllerResponse>* PrepareAsyncEnableControllerRaw(::grpc::ClientContext* context, const ::controller::EnableControllerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::controller::IsEnabledControllerResponse>* AsyncIsEnabledControllerRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::controller::IsEnabledControllerResponse>* PrepareAsyncIsEnabledControllerRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetVersion_;
    const ::grpc::internal::RpcMethod rpcmethod_ClearError_;
    const ::grpc::internal::RpcMethod rpcmethod_EnableController_;
    const ::grpc::internal::RpcMethod rpcmethod_IsEnabledController_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetVersion(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::controller::VersionResponse* response);
    virtual ::grpc::Status ClearError(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::controller::ErrorClearResponse* response);
    virtual ::grpc::Status EnableController(::grpc::ServerContext* context, const ::controller::EnableControllerRequest* request, ::controller::EnableControllerResponse* response);
    virtual ::grpc::Status IsEnabledController(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::controller::IsEnabledControllerResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetVersion() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVersion(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::VersionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetVersion(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::controller::VersionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ClearError : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ClearError() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ClearError() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClearError(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::ErrorClearResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestClearError(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::controller::ErrorClearResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_EnableController : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_EnableController() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_EnableController() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnableController(::grpc::ServerContext* /*context*/, const ::controller::EnableControllerRequest* /*request*/, ::controller::EnableControllerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEnableController(::grpc::ServerContext* context, ::controller::EnableControllerRequest* request, ::grpc::ServerAsyncResponseWriter< ::controller::EnableControllerResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_IsEnabledController : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_IsEnabledController() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_IsEnabledController() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsEnabledController(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::IsEnabledControllerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIsEnabledController(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::controller::IsEnabledControllerResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetVersion<WithAsyncMethod_ClearError<WithAsyncMethod_EnableController<WithAsyncMethod_IsEnabledController<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetVersion() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::controller::VersionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::controller::VersionResponse* response) { return this->GetVersion(context, request, response); }));}
    void SetMessageAllocatorFor_GetVersion(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::controller::VersionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::controller::VersionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVersion(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::VersionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetVersion(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::VersionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ClearError : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ClearError() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::controller::ErrorClearResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::controller::ErrorClearResponse* response) { return this->ClearError(context, request, response); }));}
    void SetMessageAllocatorFor_ClearError(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::controller::ErrorClearResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::controller::ErrorClearResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ClearError() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClearError(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::ErrorClearResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ClearError(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::ErrorClearResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_EnableController : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_EnableController() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::controller::EnableControllerRequest, ::controller::EnableControllerResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::controller::EnableControllerRequest* request, ::controller::EnableControllerResponse* response) { return this->EnableController(context, request, response); }));}
    void SetMessageAllocatorFor_EnableController(
        ::grpc::MessageAllocator< ::controller::EnableControllerRequest, ::controller::EnableControllerResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::controller::EnableControllerRequest, ::controller::EnableControllerResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_EnableController() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnableController(::grpc::ServerContext* /*context*/, const ::controller::EnableControllerRequest* /*request*/, ::controller::EnableControllerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EnableController(
      ::grpc::CallbackServerContext* /*context*/, const ::controller::EnableControllerRequest* /*request*/, ::controller::EnableControllerResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_IsEnabledController : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_IsEnabledController() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::controller::IsEnabledControllerResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::controller::IsEnabledControllerResponse* response) { return this->IsEnabledController(context, request, response); }));}
    void SetMessageAllocatorFor_IsEnabledController(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::controller::IsEnabledControllerResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::controller::IsEnabledControllerResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_IsEnabledController() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsEnabledController(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::IsEnabledControllerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* IsEnabledController(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::IsEnabledControllerResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetVersion<WithCallbackMethod_ClearError<WithCallbackMethod_EnableController<WithCallbackMethod_IsEnabledController<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetVersion() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVersion(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::VersionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ClearError : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ClearError() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ClearError() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClearError(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::ErrorClearResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_EnableController : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_EnableController() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_EnableController() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnableController(::grpc::ServerContext* /*context*/, const ::controller::EnableControllerRequest* /*request*/, ::controller::EnableControllerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_IsEnabledController : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_IsEnabledController() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_IsEnabledController() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsEnabledController(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::IsEnabledControllerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetVersion() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVersion(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::VersionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetVersion(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ClearError : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ClearError() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ClearError() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClearError(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::ErrorClearResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestClearError(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_EnableController : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_EnableController() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_EnableController() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnableController(::grpc::ServerContext* /*context*/, const ::controller::EnableControllerRequest* /*request*/, ::controller::EnableControllerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEnableController(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_IsEnabledController : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_IsEnabledController() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_IsEnabledController() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsEnabledController(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::IsEnabledControllerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIsEnabledController(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetVersion() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetVersion(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVersion(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::VersionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetVersion(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ClearError : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ClearError() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ClearError(context, request, response); }));
    }
    ~WithRawCallbackMethod_ClearError() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClearError(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::ErrorClearResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ClearError(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_EnableController : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_EnableController() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->EnableController(context, request, response); }));
    }
    ~WithRawCallbackMethod_EnableController() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnableController(::grpc::ServerContext* /*context*/, const ::controller::EnableControllerRequest* /*request*/, ::controller::EnableControllerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EnableController(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_IsEnabledController : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_IsEnabledController() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->IsEnabledController(context, request, response); }));
    }
    ~WithRawCallbackMethod_IsEnabledController() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsEnabledController(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::IsEnabledControllerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* IsEnabledController(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetVersion() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::controller::VersionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::controller::VersionResponse>* streamer) {
                       return this->StreamedGetVersion(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetVersion(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::VersionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetVersion(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::controller::VersionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ClearError : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ClearError() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::controller::ErrorClearResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::controller::ErrorClearResponse>* streamer) {
                       return this->StreamedClearError(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ClearError() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ClearError(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::ErrorClearResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedClearError(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::controller::ErrorClearResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_EnableController : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_EnableController() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::controller::EnableControllerRequest, ::controller::EnableControllerResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::controller::EnableControllerRequest, ::controller::EnableControllerResponse>* streamer) {
                       return this->StreamedEnableController(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_EnableController() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status EnableController(::grpc::ServerContext* /*context*/, const ::controller::EnableControllerRequest* /*request*/, ::controller::EnableControllerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEnableController(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::controller::EnableControllerRequest,::controller::EnableControllerResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_IsEnabledController : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_IsEnabledController() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::controller::IsEnabledControllerResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::controller::IsEnabledControllerResponse>* streamer) {
                       return this->StreamedIsEnabledController(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_IsEnabledController() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status IsEnabledController(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::controller::IsEnabledControllerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedIsEnabledController(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::controller::IsEnabledControllerResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetVersion<WithStreamedUnaryMethod_ClearError<WithStreamedUnaryMethod_EnableController<WithStreamedUnaryMethod_IsEnabledController<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetVersion<WithStreamedUnaryMethod_ClearError<WithStreamedUnaryMethod_EnableController<WithStreamedUnaryMethod_IsEnabledController<Service > > > > StreamedService;
};

}  // namespace controller


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_system_5fservice_2eproto__INCLUDED
