// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: system_service.proto
// Protobuf C++ Version: 5.29.0

#include "system_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace controller {
              template <typename>
PROTOBUF_CONSTEXPR VersionResponse_PluginsEntry_DoNotUse::VersionResponse_PluginsEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : VersionResponse_PluginsEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : VersionResponse_PluginsEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct VersionResponse_PluginsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VersionResponse_PluginsEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VersionResponse_PluginsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    VersionResponse_PluginsEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VersionResponse_PluginsEntry_DoNotUseDefaultTypeInternal _VersionResponse_PluginsEntry_DoNotUse_default_instance_;

inline constexpr IsEnabledControllerResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : enable_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR IsEnabledControllerResponse::IsEnabledControllerResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct IsEnabledControllerResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IsEnabledControllerResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~IsEnabledControllerResponseDefaultTypeInternal() {}
  union {
    IsEnabledControllerResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IsEnabledControllerResponseDefaultTypeInternal _IsEnabledControllerResponse_default_instance_;

inline constexpr ErrorClearResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ErrorClearResponse::ErrorClearResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ErrorClearResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ErrorClearResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ErrorClearResponseDefaultTypeInternal() {}
  union {
    ErrorClearResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ErrorClearResponseDefaultTypeInternal _ErrorClearResponse_default_instance_;

inline constexpr EnableControllerResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EnableControllerResponse::EnableControllerResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EnableControllerResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnableControllerResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnableControllerResponseDefaultTypeInternal() {}
  union {
    EnableControllerResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnableControllerResponseDefaultTypeInternal _EnableControllerResponse_default_instance_;

inline constexpr EnableControllerRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : enable_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EnableControllerRequest::EnableControllerRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EnableControllerRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnableControllerRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnableControllerRequestDefaultTypeInternal() {}
  union {
    EnableControllerRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnableControllerRequestDefaultTypeInternal _EnableControllerRequest_default_instance_;

inline constexpr VersionResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : plugins_{},
        main_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR VersionResponse::VersionResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct VersionResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VersionResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VersionResponseDefaultTypeInternal() {}
  union {
    VersionResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VersionResponseDefaultTypeInternal _VersionResponse_default_instance_;
}  // namespace controller
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_system_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_system_5fservice_2eproto = nullptr;
const ::uint32_t
    TableStruct_system_5fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::controller::VersionResponse_PluginsEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::controller::VersionResponse_PluginsEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::controller::VersionResponse_PluginsEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::controller::VersionResponse_PluginsEntry_DoNotUse, _impl_.value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::controller::VersionResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::controller::VersionResponse, _impl_.main_),
        PROTOBUF_FIELD_OFFSET(::controller::VersionResponse, _impl_.plugins_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::controller::ErrorClearResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::controller::ErrorClearResponse, _impl_.success_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::controller::EnableControllerRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::controller::EnableControllerRequest, _impl_.enable_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::controller::EnableControllerResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::controller::EnableControllerResponse, _impl_.success_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::controller::IsEnabledControllerResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::controller::IsEnabledControllerResponse, _impl_.enable_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::controller::VersionResponse_PluginsEntry_DoNotUse)},
        {12, -1, -1, sizeof(::controller::VersionResponse)},
        {22, -1, -1, sizeof(::controller::ErrorClearResponse)},
        {31, -1, -1, sizeof(::controller::EnableControllerRequest)},
        {40, -1, -1, sizeof(::controller::EnableControllerResponse)},
        {49, -1, -1, sizeof(::controller::IsEnabledControllerResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::controller::_VersionResponse_PluginsEntry_DoNotUse_default_instance_._instance,
    &::controller::_VersionResponse_default_instance_._instance,
    &::controller::_ErrorClearResponse_default_instance_._instance,
    &::controller::_EnableControllerRequest_default_instance_._instance,
    &::controller::_EnableControllerResponse_default_instance_._instance,
    &::controller::_IsEnabledControllerResponse_default_instance_._instance,
};
const char descriptor_table_protodef_system_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024system_service.proto\022\ncontroller\032\033goog"
    "le/protobuf/empty.proto\"\212\001\n\017VersionRespo"
    "nse\022\014\n\004main\030\001 \001(\t\0229\n\007plugins\030\002 \003(\0132(.con"
    "troller.VersionResponse.PluginsEntry\032.\n\014"
    "PluginsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t"
    ":\0028\001\"%\n\022ErrorClearResponse\022\017\n\007success\030\001 "
    "\001(\010\")\n\027EnableControllerRequest\022\016\n\006enable"
    "\030\001 \001(\010\"+\n\030EnableControllerResponse\022\017\n\007su"
    "ccess\030\001 \001(\010\"-\n\033IsEnabledControllerRespon"
    "se\022\016\n\006enable\030\001 \001(\0102\327\002\n\rSystemService\022C\n\n"
    "GetVersion\022\026.google.protobuf.Empty\032\033.con"
    "troller.VersionResponse\"\000\022F\n\nClearError\022"
    "\026.google.protobuf.Empty\032\036.controller.Err"
    "orClearResponse\"\000\022_\n\020EnableController\022#."
    "controller.EnableControllerRequest\032$.con"
    "troller.EnableControllerResponse\"\000\022X\n\023Is"
    "EnabledController\022\026.google.protobuf.Empt"
    "y\032\'.controller.IsEnabledControllerRespon"
    "se\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_system_5fservice_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_system_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_system_5fservice_2eproto = {
    false,
    false,
    732,
    descriptor_table_protodef_system_5fservice_2eproto,
    "system_service.proto",
    &descriptor_table_system_5fservice_2eproto_once,
    descriptor_table_system_5fservice_2eproto_deps,
    1,
    6,
    schemas,
    file_default_instances,
    TableStruct_system_5fservice_2eproto::offsets,
    file_level_enum_descriptors_system_5fservice_2eproto,
    file_level_service_descriptors_system_5fservice_2eproto,
};
namespace controller {
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              VersionResponse_PluginsEntry_DoNotUse::VersionResponse_PluginsEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              VersionResponse_PluginsEntry_DoNotUse::VersionResponse_PluginsEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              VersionResponse_PluginsEntry_DoNotUse::VersionResponse_PluginsEntry_DoNotUse() : SuperType() {}
              VersionResponse_PluginsEntry_DoNotUse::VersionResponse_PluginsEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* VersionResponse_PluginsEntry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) VersionResponse_PluginsEntry_DoNotUse(arena);
              }
              constexpr auto VersionResponse_PluginsEntry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VersionResponse_PluginsEntry_DoNotUse),
                                                          alignof(VersionResponse_PluginsEntry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull VersionResponse_PluginsEntry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_VersionResponse_PluginsEntry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &VersionResponse_PluginsEntry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<VersionResponse_PluginsEntry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &VersionResponse_PluginsEntry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &VersionResponse_PluginsEntry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(VersionResponse_PluginsEntry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &VersionResponse_PluginsEntry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_system_5fservice_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* VersionResponse_PluginsEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 56, 2> VersionResponse_PluginsEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(VersionResponse_PluginsEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::controller::VersionResponse_PluginsEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string value = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(VersionResponse_PluginsEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(VersionResponse_PluginsEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(VersionResponse_PluginsEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string value = 2;
    {PROTOBUF_FIELD_OFFSET(VersionResponse_PluginsEntry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\47\3\5\0\0\0\0\0"
    "controller.VersionResponse.PluginsEntry"
    "key"
    "value"
  }},
};

// ===================================================================

class VersionResponse::_Internal {
 public:
};

VersionResponse::VersionResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:controller.VersionResponse)
}
inline PROTOBUF_NDEBUG_INLINE VersionResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::controller::VersionResponse& from_msg)
      : plugins_{visibility, arena, from.plugins_},
        main_(arena, from.main_),
        _cached_size_{0} {}

VersionResponse::VersionResponse(
    ::google::protobuf::Arena* arena,
    const VersionResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VersionResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:controller.VersionResponse)
}
inline PROTOBUF_NDEBUG_INLINE VersionResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : plugins_{visibility, arena},
        main_(arena),
        _cached_size_{0} {}

inline void VersionResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
VersionResponse::~VersionResponse() {
  // @@protoc_insertion_point(destructor:controller.VersionResponse)
  SharedDtor(*this);
}
inline void VersionResponse::SharedDtor(MessageLite& self) {
  VersionResponse& this_ = static_cast<VersionResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.main_.Destroy();
  this_._impl_.~Impl_();
}

inline void* VersionResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) VersionResponse(arena);
}
constexpr auto VersionResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(VersionResponse, _impl_.plugins_) +
          decltype(VersionResponse::_impl_.plugins_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(VersionResponse, _impl_.plugins_) +
          decltype(VersionResponse::_impl_.plugins_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(VersionResponse), alignof(VersionResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&VersionResponse::PlacementNew_,
                                 sizeof(VersionResponse),
                                 alignof(VersionResponse));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull VersionResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_VersionResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &VersionResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<VersionResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &VersionResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<VersionResponse>(), &VersionResponse::ByteSizeLong,
            &VersionResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(VersionResponse, _impl_._cached_size_),
        false,
    },
    &VersionResponse::kDescriptorMethods,
    &descriptor_table_system_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* VersionResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 1, 46, 2> VersionResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::controller::VersionResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string main = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(VersionResponse, _impl_.main_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string main = 1;
    {PROTOBUF_FIELD_OFFSET(VersionResponse, _impl_.main_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // map<string, string> plugins = 2;
    {PROTOBUF_FIELD_OFFSET(VersionResponse, _impl_.plugins_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(VersionResponse()._impl_.plugins_)>(
        1, 0, 0, 9,
        9)},
  }}, {{
    "\32\4\7\0\0\0\0\0"
    "controller.VersionResponse"
    "main"
    "plugins"
  }},
};

PROTOBUF_NOINLINE void VersionResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:controller.VersionResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.plugins_.Clear();
  _impl_.main_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* VersionResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const VersionResponse& this_ = static_cast<const VersionResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* VersionResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const VersionResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:controller.VersionResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string main = 1;
          if (!this_._internal_main().empty()) {
            const std::string& _s = this_._internal_main();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "controller.VersionResponse.main");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // map<string, string> plugins = 2;
          if (!this_._internal_plugins().empty()) {
            using MapType = ::google::protobuf::Map<std::string, std::string>;
            using WireHelper = _pbi::MapEntryFuncs<std::string, std::string,
                                           _pbi::WireFormatLite::TYPE_STRING,
                                           _pbi::WireFormatLite::TYPE_STRING>;
            const auto& field = this_._internal_plugins();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    2, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "controller.VersionResponse.plugins");
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "controller.VersionResponse.plugins");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    2, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "controller.VersionResponse.plugins");
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "controller.VersionResponse.plugins");
              }
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:controller.VersionResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t VersionResponse::ByteSizeLong(const MessageLite& base) {
          const VersionResponse& this_ = static_cast<const VersionResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t VersionResponse::ByteSizeLong() const {
          const VersionResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:controller.VersionResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // map<string, string> plugins = 2;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_plugins_size());
              for (const auto& entry : this_._internal_plugins()) {
                total_size += _pbi::MapEntryFuncs<std::string, std::string,
                                               _pbi::WireFormatLite::TYPE_STRING,
                                               _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
           {
            // string main = 1;
            if (!this_._internal_main().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_main());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void VersionResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<VersionResponse*>(&to_msg);
  auto& from = static_cast<const VersionResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:controller.VersionResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.plugins_.MergeFrom(from._impl_.plugins_);
  if (!from._internal_main().empty()) {
    _this->_internal_set_main(from._internal_main());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void VersionResponse::CopyFrom(const VersionResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:controller.VersionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void VersionResponse::InternalSwap(VersionResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.plugins_.InternalSwap(&other->_impl_.plugins_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.main_, &other->_impl_.main_, arena);
}

::google::protobuf::Metadata VersionResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ErrorClearResponse::_Internal {
 public:
};

ErrorClearResponse::ErrorClearResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:controller.ErrorClearResponse)
}
ErrorClearResponse::ErrorClearResponse(
    ::google::protobuf::Arena* arena, const ErrorClearResponse& from)
    : ErrorClearResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ErrorClearResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ErrorClearResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
ErrorClearResponse::~ErrorClearResponse() {
  // @@protoc_insertion_point(destructor:controller.ErrorClearResponse)
  SharedDtor(*this);
}
inline void ErrorClearResponse::SharedDtor(MessageLite& self) {
  ErrorClearResponse& this_ = static_cast<ErrorClearResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ErrorClearResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ErrorClearResponse(arena);
}
constexpr auto ErrorClearResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ErrorClearResponse),
                                            alignof(ErrorClearResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ErrorClearResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ErrorClearResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ErrorClearResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ErrorClearResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ErrorClearResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ErrorClearResponse>(), &ErrorClearResponse::ByteSizeLong,
            &ErrorClearResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ErrorClearResponse, _impl_._cached_size_),
        false,
    },
    &ErrorClearResponse::kDescriptorMethods,
    &descriptor_table_system_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ErrorClearResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ErrorClearResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::controller::ErrorClearResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ErrorClearResponse, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ErrorClearResponse, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(ErrorClearResponse, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ErrorClearResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:controller.ErrorClearResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ErrorClearResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ErrorClearResponse& this_ = static_cast<const ErrorClearResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ErrorClearResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ErrorClearResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:controller.ErrorClearResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool success = 1;
          if (this_._internal_success() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_success(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:controller.ErrorClearResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ErrorClearResponse::ByteSizeLong(const MessageLite& base) {
          const ErrorClearResponse& this_ = static_cast<const ErrorClearResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ErrorClearResponse::ByteSizeLong() const {
          const ErrorClearResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:controller.ErrorClearResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bool success = 1;
            if (this_._internal_success() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ErrorClearResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ErrorClearResponse*>(&to_msg);
  auto& from = static_cast<const ErrorClearResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:controller.ErrorClearResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ErrorClearResponse::CopyFrom(const ErrorClearResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:controller.ErrorClearResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ErrorClearResponse::InternalSwap(ErrorClearResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata ErrorClearResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EnableControllerRequest::_Internal {
 public:
};

EnableControllerRequest::EnableControllerRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:controller.EnableControllerRequest)
}
EnableControllerRequest::EnableControllerRequest(
    ::google::protobuf::Arena* arena, const EnableControllerRequest& from)
    : EnableControllerRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE EnableControllerRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void EnableControllerRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.enable_ = {};
}
EnableControllerRequest::~EnableControllerRequest() {
  // @@protoc_insertion_point(destructor:controller.EnableControllerRequest)
  SharedDtor(*this);
}
inline void EnableControllerRequest::SharedDtor(MessageLite& self) {
  EnableControllerRequest& this_ = static_cast<EnableControllerRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* EnableControllerRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EnableControllerRequest(arena);
}
constexpr auto EnableControllerRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(EnableControllerRequest),
                                            alignof(EnableControllerRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EnableControllerRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EnableControllerRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EnableControllerRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EnableControllerRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EnableControllerRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EnableControllerRequest>(), &EnableControllerRequest::ByteSizeLong,
            &EnableControllerRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EnableControllerRequest, _impl_._cached_size_),
        false,
    },
    &EnableControllerRequest::kDescriptorMethods,
    &descriptor_table_system_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EnableControllerRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> EnableControllerRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::controller::EnableControllerRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool enable = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(EnableControllerRequest, _impl_.enable_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(EnableControllerRequest, _impl_.enable_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool enable = 1;
    {PROTOBUF_FIELD_OFFSET(EnableControllerRequest, _impl_.enable_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void EnableControllerRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:controller.EnableControllerRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.enable_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EnableControllerRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EnableControllerRequest& this_ = static_cast<const EnableControllerRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EnableControllerRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EnableControllerRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:controller.EnableControllerRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool enable = 1;
          if (this_._internal_enable() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_enable(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:controller.EnableControllerRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EnableControllerRequest::ByteSizeLong(const MessageLite& base) {
          const EnableControllerRequest& this_ = static_cast<const EnableControllerRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EnableControllerRequest::ByteSizeLong() const {
          const EnableControllerRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:controller.EnableControllerRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bool enable = 1;
            if (this_._internal_enable() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EnableControllerRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EnableControllerRequest*>(&to_msg);
  auto& from = static_cast<const EnableControllerRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:controller.EnableControllerRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_enable() != 0) {
    _this->_impl_.enable_ = from._impl_.enable_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EnableControllerRequest::CopyFrom(const EnableControllerRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:controller.EnableControllerRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EnableControllerRequest::InternalSwap(EnableControllerRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.enable_, other->_impl_.enable_);
}

::google::protobuf::Metadata EnableControllerRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EnableControllerResponse::_Internal {
 public:
};

EnableControllerResponse::EnableControllerResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:controller.EnableControllerResponse)
}
EnableControllerResponse::EnableControllerResponse(
    ::google::protobuf::Arena* arena, const EnableControllerResponse& from)
    : EnableControllerResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE EnableControllerResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void EnableControllerResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
EnableControllerResponse::~EnableControllerResponse() {
  // @@protoc_insertion_point(destructor:controller.EnableControllerResponse)
  SharedDtor(*this);
}
inline void EnableControllerResponse::SharedDtor(MessageLite& self) {
  EnableControllerResponse& this_ = static_cast<EnableControllerResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* EnableControllerResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EnableControllerResponse(arena);
}
constexpr auto EnableControllerResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(EnableControllerResponse),
                                            alignof(EnableControllerResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EnableControllerResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EnableControllerResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EnableControllerResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EnableControllerResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EnableControllerResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EnableControllerResponse>(), &EnableControllerResponse::ByteSizeLong,
            &EnableControllerResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EnableControllerResponse, _impl_._cached_size_),
        false,
    },
    &EnableControllerResponse::kDescriptorMethods,
    &descriptor_table_system_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EnableControllerResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> EnableControllerResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::controller::EnableControllerResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(EnableControllerResponse, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(EnableControllerResponse, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(EnableControllerResponse, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void EnableControllerResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:controller.EnableControllerResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EnableControllerResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EnableControllerResponse& this_ = static_cast<const EnableControllerResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EnableControllerResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EnableControllerResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:controller.EnableControllerResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool success = 1;
          if (this_._internal_success() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_success(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:controller.EnableControllerResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EnableControllerResponse::ByteSizeLong(const MessageLite& base) {
          const EnableControllerResponse& this_ = static_cast<const EnableControllerResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EnableControllerResponse::ByteSizeLong() const {
          const EnableControllerResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:controller.EnableControllerResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bool success = 1;
            if (this_._internal_success() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EnableControllerResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EnableControllerResponse*>(&to_msg);
  auto& from = static_cast<const EnableControllerResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:controller.EnableControllerResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EnableControllerResponse::CopyFrom(const EnableControllerResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:controller.EnableControllerResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EnableControllerResponse::InternalSwap(EnableControllerResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata EnableControllerResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class IsEnabledControllerResponse::_Internal {
 public:
};

IsEnabledControllerResponse::IsEnabledControllerResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:controller.IsEnabledControllerResponse)
}
IsEnabledControllerResponse::IsEnabledControllerResponse(
    ::google::protobuf::Arena* arena, const IsEnabledControllerResponse& from)
    : IsEnabledControllerResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE IsEnabledControllerResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void IsEnabledControllerResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.enable_ = {};
}
IsEnabledControllerResponse::~IsEnabledControllerResponse() {
  // @@protoc_insertion_point(destructor:controller.IsEnabledControllerResponse)
  SharedDtor(*this);
}
inline void IsEnabledControllerResponse::SharedDtor(MessageLite& self) {
  IsEnabledControllerResponse& this_ = static_cast<IsEnabledControllerResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* IsEnabledControllerResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) IsEnabledControllerResponse(arena);
}
constexpr auto IsEnabledControllerResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(IsEnabledControllerResponse),
                                            alignof(IsEnabledControllerResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull IsEnabledControllerResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_IsEnabledControllerResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &IsEnabledControllerResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<IsEnabledControllerResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &IsEnabledControllerResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<IsEnabledControllerResponse>(), &IsEnabledControllerResponse::ByteSizeLong,
            &IsEnabledControllerResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(IsEnabledControllerResponse, _impl_._cached_size_),
        false,
    },
    &IsEnabledControllerResponse::kDescriptorMethods,
    &descriptor_table_system_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* IsEnabledControllerResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> IsEnabledControllerResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::controller::IsEnabledControllerResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool enable = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(IsEnabledControllerResponse, _impl_.enable_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(IsEnabledControllerResponse, _impl_.enable_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool enable = 1;
    {PROTOBUF_FIELD_OFFSET(IsEnabledControllerResponse, _impl_.enable_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void IsEnabledControllerResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:controller.IsEnabledControllerResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.enable_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* IsEnabledControllerResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const IsEnabledControllerResponse& this_ = static_cast<const IsEnabledControllerResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* IsEnabledControllerResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const IsEnabledControllerResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:controller.IsEnabledControllerResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool enable = 1;
          if (this_._internal_enable() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_enable(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:controller.IsEnabledControllerResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t IsEnabledControllerResponse::ByteSizeLong(const MessageLite& base) {
          const IsEnabledControllerResponse& this_ = static_cast<const IsEnabledControllerResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t IsEnabledControllerResponse::ByteSizeLong() const {
          const IsEnabledControllerResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:controller.IsEnabledControllerResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bool enable = 1;
            if (this_._internal_enable() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void IsEnabledControllerResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<IsEnabledControllerResponse*>(&to_msg);
  auto& from = static_cast<const IsEnabledControllerResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:controller.IsEnabledControllerResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_enable() != 0) {
    _this->_impl_.enable_ = from._impl_.enable_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void IsEnabledControllerResponse::CopyFrom(const IsEnabledControllerResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:controller.IsEnabledControllerResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void IsEnabledControllerResponse::InternalSwap(IsEnabledControllerResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.enable_, other->_impl_.enable_);
}

::google::protobuf::Metadata IsEnabledControllerResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace controller
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_system_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
